 
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username":"berkkan2",
    "email":"berkkan2@gmail.com",
    "password":"12345678a"
}
###
GET http://localhost:3000/api/auth/me